# Generated by Django 5.1.3 on 2024-11-25 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='end_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_location_here', to='routes.location'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='start_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_location_here', to='routes.location'),
        ),
    ]
